Create a workflow to run repoaudit
microsoft/linux-package-repositories pull request #2
Opened 2022-03-07 18:46 UTC by daviddavis

2022-03-15 01:40 UTC, jasonzio requested changes

2022-03-15 01:40 UTC, jasonzio commented on repoaudit/repoaudit/__init__.py
> +        dist_set = None
None, or `set()`, i.e. empty set?

2022-05-12 19:16 UTC, mbearup approved these changes

2022-05-12 19:19 UTC, jasonzio approved these changes

2022-05-12 19:19 UTC, merged